// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // The dev DB is always ./dev.db, and the build/electron pass DATABASE_URL
    // inline where a different path is needed — so fall back to ./dev.db and the
    // Prisma CLI works without a DATABASE_URL in the environment (.env removed).
    url: process.env["DATABASE_URL"] ?? "file:./dev.db",
  },
});
